myValue = (int)(input("Enter your value"))
c = input('Enter your character')
print("The binary value is", bin(myValue))
print("The hexidecimal value is", hex(myValue))
print("The ASCII value is", ord(c))
