myValue = (int)(input('Enter your value'))
c = input('Enter your character')
print("The binary value of '" + myValue + "' is", bin(myValue))
print("The hexidecimal value of '" + myValue + "' is", hex(myValue))
print("The ASCII value of '" + c + "' is", ord(c))
